//Generated by Ironbug.PythonConverter
namespace Honeybee.Radiance.Command
{

	// this is a class
	public class RaBmp : RadianceCommand
    {
		// this is a class Property
		public object RaBmpParameters
		{
			get { return this.RawObj.raBmpParameters; }
			set { this.RawObj.raBmpParameters = value; }
		}

		// this is a class Property
		public object InputFiles
		{
			get { return this.RawObj.inputFiles; }
			set { this.RawObj.inputFiles = value; }
		}

		// this is a class constructor
		public RaBmp(object InputHdrFile , object OutputBmpFile , object RaBmpParameters)
		{
			PythonEngine engine = new PythonEngine();
			dynamic pyModule = engine.ImportFrom(From: "Honeybee.Radiance.Command", Import: "RaBmp");

			if (pyModule != null)
			{
				this.RawObj = pyModule(InputHdrFile , OutputBmpFile , RaBmpParameters);
			}

		}

		// this is a class method
		public override object ToRadString(bool RelativePath = False)
		{
			return base.toRadString(RelativePath);
		}




    }



} //namespace

