//Generated by Ironbug.PythonConverter
namespace Honeybee.Radiance.Recipe
{
	// this is a default static class for holding Valuables and Functions
	public static class Parameters
	{
		// this is a Valuables
		List<object> DCDEFAULTS = IronPython.Runtime.List;

		// this is a Valuables
		List<object> DMDEFAULTS = IronPython.Runtime.List;

		// this is a Valuables
		List<object> IMGDCDEFAULTS = IronPython.Runtime.List;

		// this is a Valuables
		List<object> IMGVMDEFAULTS = IronPython.Runtime.List;

		// this is a Valuables
		Dictionary<string,object> SMDEFAULTS = IronPython.Runtime.PythonDictionary;

		// this is a Valuables
		List<object> VMDEFAULTS = IronPython.Runtime.List;



		// this is a Function
		public static  object GetRadianceParametersGridBased(object Quality , object RecType)
		{
			return base.getRadianceParametersGridBased(Quality , RecType);
		}

		// this is a Function
		public static  object GetRadianceParametersImageBased(object Quality , object RecType)
		{
			return base.getRadianceParametersImageBased(Quality , RecType);
		}

	}//end of default static class




} //namespace

