//Generated by Ironbug.PythonConverter
namespace Honeybee.Radiance.Command
{

	// this is a class
	public class Epw2wea : RadianceCommand
    {
		// this is a class Property
		public object EpwFile
		{
			get { return this.RawObj.epwFile; }
			set { this.RawObj.epwFile = value; }
		}

		// this is a class Property
		public object InputFiles
		{
			get { return this.RawObj.inputFiles; }
			set { this.RawObj.inputFiles = value; }
		}

		// this is a class constructor
		public Epw2wea(object EpwFile, object OutputWeaFile)
		{
			PythonEngine engine = new PythonEngine();
			dynamic pyModule = engine.ImportFrom(From: "honeybee.radiance.command.epw2wea", Import: "Epw2wea");

			if (pyModule != null)
			{
				this.RawObj = pyModule(EpwFile, OutputWeaFile);
			}

		}

		// this is a class method
		public override object ToRadString(bool RelativePath = False)
		{
			return base.toRadString(RelativePath);
		}




    }



} //namespace

