//Generated by Ironbug.PythonConverter
namespace Ladybug
{
	// this is a default static class for holding Valuables and Functions
	public static class Wea
	{


	}//end of default static class

	// this is a class
	public class Wea : object
    {
		// this is a class Property
		public object IsWea
		{
			get { return this.RawObj.isWea; }
			set { this.RawObj.isWea = value; }
		}

		// this is a class Property
		public object Header
		{
			get { return this.RawObj.header; }
			set { this.RawObj.header = value; }
		}

		// this is a class constructor
		public Wea(int Timestep = 1)
		{
			PythonEngine engine = new PythonEngine();
			dynamic pyModule = engine.ImportFrom(From: "ladybug.wea", Import: "Wea");

			if (pyModule != null)
			{
				this.RawObj = pyModule(Timestep);
			}

		}

		// this is a class method
		public  void FromEpwFile(object Cls, object Epwfile)
		{
			base.fromEpwFile(Cls, Epwfile);
		}
		// this is a class method
		public  object GetRadiationValues(object Month, object Day, object Hour)
		{
			return base.getRadiationValues(Month, Day, Hour);
		}
		// this is a class method
		public  object GetRadiationValuesForHoy(object Hoy)
		{
			return base.getRadiationValuesForHoy(Hoy);
		}
		// this is a class method
		public  object Write(object Hoys, bool WriteHours = False)
		{
			return base.write(Hoys, WriteHours);
		}
		// this is a class method
		public  object ToString()
		{
			return base.ToString();
		}
		// this is a class method
		public override object __repr__()
		{
			return base.__repr__();
		}




    }



} //namespace

